# Python資料分析絕對繞不過的四個包是
## numpy、scipy、pandas還有matplotlib

## numpy是Python數值計算

In [30]:
import numpy as np

## PART1 : numpy組成

##### case1 np.array 其成分

In [2]:
data = np.array([[1, 2, 3, 4, 5, 6],[1, 2, 3, 4, 5, 6]])
print(' 幾維陣列 : %s\n'%str(data.ndim) , '元素組成 : %s\n'%str(data.shape), '幾個元素 : %s\n'%str(data.size), '資料型別 : %s\n'%str(data.dtype)) # 一維陣列, 三個元素, 資料型別

 幾維陣列 : 2
 元素組成 : (2, 6)
 幾個元素 : 12
 資料型別 : int32



##### case2 array合併

In [3]:
data_A = np.array([[1, 2],[3, 4]])
data_B = np.array([[1, 1],[1, 1]])

In [4]:
np.vstack((data_A,data_B))

array([[1, 2],
       [3, 4],
       [1, 1],
       [1, 1]])

In [5]:
np.hstack((data_A,data_B))

array([[1, 2, 1, 1],
       [3, 4, 1, 1]])

##### case3 array reshape

In [6]:
ndarray = np.arange(2,11).reshape(3,3)
ndarray

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

##### case4

In [7]:
iris_data = np.genfromtxt('C:/Users/student/Desktop/github/data-analysis/iris.csv', delimiter=',')

In [8]:
iris_data_part = iris_data[0:5]
iris_data_part

array([[nan, nan, nan, nan, nan],
       [5.1, 3.5, 1.4, 0.2, nan],
       [4.9, 3. , 1.4, 0.2, nan],
       [4.7, 3.2, 1.3, 0.2, nan],
       [4.6, 3.1, 1.5, 0.2, nan]])

In [9]:
iris_data_part[:][0:2]

array([[nan, nan, nan, nan, nan],
       [5.1, 3.5, 1.4, 0.2, nan]])

In [10]:
iris_data_part[:,0:2]

array([[nan, nan],
       [5.1, 3.5],
       [4.9, 3. ],
       [4.7, 3.2],
       [4.6, 3.1]])

In [11]:
iris_data_part2 = np.delete(iris_data_part,1,axis = 0)#删除 的第二行
iris_data_part2

array([[nan, nan, nan, nan, nan],
       [4.9, 3. , 1.4, 0.2, nan],
       [4.7, 3.2, 1.3, 0.2, nan],
       [4.6, 3.1, 1.5, 0.2, nan]])

In [12]:
iris_data_part3 = np.delete(iris_data_part,(1,2),0)#删除 的第二，三行
iris_data_part3

array([[nan, nan, nan, nan, nan],
       [4.7, 3.2, 1.3, 0.2, nan],
       [4.6, 3.1, 1.5, 0.2, nan]])

In [13]:
iris_data_part4 = np.delete(iris_data_part,1,axis = 1)#删除 的第二列
iris_data_part4

array([[nan, nan, nan, nan],
       [5.1, 1.4, 0.2, nan],
       [4.9, 1.4, 0.2, nan],
       [4.7, 1.3, 0.2, nan],
       [4.6, 1.5, 0.2, nan]])

##### case5

In [14]:
label_1 = np.zeros([50, 1]) # 0
label_2 = np.ones([50, 1]) # 1
label_3 = np.empty([50, 1]) # 空
label_4 = np.arange(6) # 6個 值依序
label_5 = np.arange(1,7,1) # 1~6 值依序 
label_6 = np.linspace(0,10,7) # 生成首位是0，末位是10，含7个数的等差数列
label_7 = np.logspace(0,4,5) #用于生成首位是10**0，末位是10**4，含5个数的等比数列

## PART2 : array reshape & 加減乘除

In [15]:
data_A = np.array([[1, 2],[3, 4]])
data_B = np.array([[1, 1],[1, 1]])

In [16]:
data_newA = data_A.reshape([1, 4])
data_newA

array([[1, 2, 3, 4]])

In [17]:
data_A.sum(axis=1)

array([3, 7])

In [18]:
print('mean : ' , np.mean(data_A))
print('median : ' , np.median(data_A))
print('min : ' , np.min(data_A))
print('max : ' , np.max(data_A))
print('std : ' , np.std(data_A))
print('var : ' , np.var(data_A))

mean :  2.5
median :  2.5
min :  1
max :  4
std :  1.118033988749895
var :  1.25


In [19]:
np.sort(np.array([5,1,3,4,2]))

array([1, 2, 3, 4, 5])

In [20]:
print(data_A + data_B)

[[2 3]
 [4 5]]


In [21]:
print(data_A - data_B)

[[0 1]
 [2 3]]


In [22]:
data_A*data_B 

array([[1, 2],
       [3, 4]])

In [23]:
np.dot(data_A,data_B)

array([[3, 3],
       [7, 7]])

In [24]:
print(np.diff(data_A)) # 相差
print('\n')
print(np.diff(data_newA))

[[1]
 [1]]


[[1 1 1]]


## PART3 : 資料位置

In [25]:
np.argmax(data_A) # 這數組最大的數字 在第幾個位置

3

In [26]:
data_A = data_A.reshape([1, 4])[0]
np.where(data_A == max(data_A))

(array([3], dtype=int64),)

In [27]:
print(data_A >= 3)
print(data_A[data_A >= 3])

[False False  True  True]
[3 4]


## PART4 : np.array to list

In [28]:
list_data_A = data_A.tolist()
list_data_A

[1, 2, 3, 4]

In [29]:
'''
更多函数all, alltrue, any, apply along axis, argmax, argmin, argsort, average, bincount, ceil, clip, conj, conjugate, corrcoef, cov, cross, cumprod, cumsum, diff, dot, floor, inner, inv, lexsort, max, maximum, mean, median, min, minimum, nonzero, outer, prod, re, round, sometrue, sort, std, sum, trace, transpose, var, vdot, vectorize, where 
参见: https://docs.scipy.org/doc/numpy/reference/routines.html
'''

'\n更多函数all, alltrue, any, apply along axis, argmax, argmin, argsort, average, bincount, ceil, clip, conj, conjugate, corrcoef, cov, cross, cumprod, cumsum, diff, dot, floor, inner, inv, lexsort, max, maximum, mean, median, min, minimum, nonzero, outer, prod, re, round, sometrue, sort, std, sum, trace, transpose, var, vdot, vectorize, where \n参见: https://docs.scipy.org/doc/numpy/reference/routines.html\n'